#spring.main.web-application-type=none
spring:
  application:
    name: kong-client

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      example:
        kongclient:
          service:
            KongAdminClient: DEBUG